<a href="https://colab.research.google.com/github/JulioGoS/Tratamiento-de-datos-con-Python/blob/main/03NumpyOperaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
m1 = np.array([[1,2,3],
              [10,11,12],
              [-5,-8,-14]])
m1

array([[  1,   2,   3],
       [ 10,  11,  12],
       [ -5,  -8, -14]])

In [4]:
# Las operaciones aritmeticas se aplican a todos los elementos de la matriz
m1*200

array([[  200,   400,   600],
       [ 2000,  2200,  2400],
       [-1000, -1600, -2800]])

In [5]:
#Aplicar la operacion a un elemento
m1[1] + 15

array([25, 26, 27])

In [6]:
m1 / 5.45

array([[ 0.18348624,  0.36697248,  0.55045872],
       [ 1.83486239,  2.01834862,  2.20183486],
       [-0.91743119, -1.46788991, -2.56880734]])

In [7]:
#Usar operadores logicos por broadcasting
m1 > 1

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [8]:
m2 = np.array([1,2,3])
m3 = np.array([[2],[4],[6]])

print(m2)
print(m2.shape)

print(m3)
print(m3.shape)

[1 2 3]
(3,)
[[2]
 [4]
 [6]]
(3, 1)


In [9]:
m1 * m2

array([[  1,   4,   9],
       [ 10,  22,  36],
       [ -5, -16, -42]])

In [10]:
m1 / m3

array([[ 0.5       ,  1.        ,  1.5       ],
       [ 2.5       ,  2.75      ,  3.        ],
       [-0.83333333, -1.33333333, -2.33333333]])

In [11]:
m4 = m1 + 20
m4

array([[21, 22, 23],
       [30, 31, 32],
       [15, 12,  6]])

In [12]:
m1 * m4

array([[ 21,  44,  69],
       [300, 341, 384],
       [-75, -96, -84]])

In [13]:
#Generar arreglos con valores aleatorios
np.random.rand(2,2,2)

array([[[0.18977121, 0.2050741 ],
        [0.42001397, 0.93518045]],

       [[0.04398465, 0.19930898],
        [0.31617447, 0.03479915]]])

In [15]:
# randint genera valores enteros aleatorios entre un rango
np.random.randint(1,4,(2,2,2))

array([[[3, 3],
        [3, 3]],

       [[3, 1],
        [3, 1]]])

In [16]:
np.random.randint(0,256,(3,2,4))

array([[[220,  16,  29, 114],
        [114, 190, 158,  71]],

       [[218, 180, 224, 119],
        [172,  41, 124, 118]],

       [[162, 211, 122, 191],
        [ 43,  62, 126, 252]]])

In [17]:
numeros = np.array([[2.43, -3, 48.9999, -5.61],
                   [np.inf, -np.inf, np.inf, np.inf],
                   [np.nan, 17.78, 12, 22]])
numeros

array([[ 2.43  , -3.    , 48.9999, -5.61  ],
       [    inf,    -inf,     inf,     inf],
       [    nan, 17.78  , 12.    , 22.    ]])

In [18]:
# Funciones de valor
print(np.abs(numeros))
print(np.floor(numeros))
print(np.ceil(numeros))
print(np.round(numeros))

[[ 2.43    3.     48.9999  5.61  ]
 [    inf     inf     inf     inf]
 [    nan 17.78   12.     22.    ]]
[[  2.  -3.  48.  -6.]
 [ inf -inf  inf  inf]
 [ nan  17.  12.  22.]]
[[  3.  -3.  49.  -5.]
 [ inf -inf  inf  inf]
 [ nan  18.  12.  22.]]
[[  2.  -3.  49.  -6.]
 [ inf -inf  inf  inf]
 [ nan  18.  12.  22.]]


In [19]:
#Funciones de evaluacion de arreglos
print(np.isfinite(numeros))
print(np.isnan(numeros))
print(np.isreal(numeros))
print(np.isscalar(numeros))

[[ True  True  True  True]
 [False False False False]
 [False  True  True  True]]
[[False False False False]
 [False False False False]
 [ True False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
False


## Funciones estadísticas.

* ```np.amax()```
* ```np amin()```
* ```np.argmax()```
* ```np.argmin()```
* ```np.average()```
* ```np.correlate()```
* ```np.corrcoef()```
* ```np.count_nonzero()```
* ```np.cov()```
* ```np.cumprod()```
* ```np.cumsum()```
* ```np.histogram()```
* ```np.histogram2d()```
* ```np.histogram_bin_edges()```
* ```np.histogramdd()```
* ```np.max()```
* ```np.mean()```
* ```np.median()```
* ```np.min()```
* ```np.nanargmax()```
* ```np.nanargmin()```
* ```np.nancumprod()```
* ```np.nancumsum()```
* ```np.nanmax()```
* ```np.nanmean()```
* ```np.nanmedian()```
* ```np.nanmin()```
* ```np.nanpercentile()```
* ```np.nanquantile()```
* ```np.nanstd()```
* ```np.nansum()```
* ```np.nanvar()```
* ```np.percentile()```
* ```np.quantile()```
* ```np.std()```
* ```np.var()```


In [21]:
numeros = np.random.randint(0,256,(3,2,4))
numeros

array([[[134,  12,  86, 101],
        [230, 120, 250, 166]],

       [[165,  19,  99,  98],
        [ 14, 211,  79,  85]],

       [[205, 137, 210, 117],
        [ 11,  33,  93, 192]]])

In [22]:
print(np.max(numeros))
print(np.mean(numeros))
print(np.min(numeros))

250
119.45833333333333
11


In [24]:
print(np.nanmax(numeros))
print(np.nanmean(numeros))
print(np.nanmin(numeros))
print(np.nanmedian(numeros))

250
119.45833333333333
11
109.0


In [25]:
np.histogram(numeros)

(array([5, 0, 1, 6, 2, 2, 2, 1, 3, 2]),
 array([ 11. ,  34.9,  58.8,  82.7, 106.6, 130.5, 154.4, 178.3, 202.2,
        226.1, 250. ]))

## Funciones de valor
* ```np.abs()```
* ```np.around()```
* ```np.ceil()```
* ```np.exp()```
* ```np.exp2()```
* ```np.fabs()```
* ```np.fix()```
* ```np.floor()```
* ```np.log()```
* ```np.log10()```
* ```np.log1p()```
* ```np.log2()```
* ```np.logaddexp()```
* ```np.logaddexp2()```
* ```np.round()```


In [26]:
# Copia y ordenamiento
numeros1 = numeros # Alias de un arreglo
numeros1 = np.copy(numeros) #Copia del arreglo
numeros1 

array([[[134,  12,  86, 101],
        [230, 120, 250, 166]],

       [[165,  19,  99,  98],
        [ 14, 211,  79,  85]],

       [[205, 137, 210, 117],
        [ 11,  33,  93, 192]]])

In [27]:
numeros1.sort()
numeros1

array([[[ 12,  86, 101, 134],
        [120, 166, 230, 250]],

       [[ 19,  98,  99, 165],
        [ 14,  79,  85, 211]],

       [[117, 137, 205, 210],
        [ 11,  33,  93, 192]]])

In [29]:
numeros1.sort(axis=2)
numeros1

array([[[ 12,  86, 101, 134],
        [120, 166, 230, 250]],

       [[ 14,  79,  85, 165],
        [ 19,  98,  99, 211]],

       [[ 11,  33,  93, 192],
        [117, 137, 205, 210]]])

In [30]:
a = np.array([1,2,3])
b = np.array([(1,2,3),(4,5,6)])
print(a)
print(b)
print(np.add(a,b))

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [5 7 9]]


In [31]:
#Suma total de los elementos
b.sum()

21

In [32]:
#Raiz cuadrada
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [33]:
# Crear un arreglo con los resultados de una comparacion logica
c = b <= 4
c

array([[ True,  True,  True],
       [ True, False, False]])